AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: The Planner API
Resources:
  Food/Meals:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: main
      CodeUri: ./endpoints/food/meals
      Events:
        Api:
          Type: Api
          Properties:
            Path: /food/meals
            Method: any
  Food/Ingredients:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: main
      CodeUri: ./endpoints/food/ingredients
      Events:
        Api:
          Type: Api
          Properties:
            Path: /food/ingredients
            Method: any
  Food/Planner:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: main
      CodeUri: ./endpoints/food/planner
      Events:
        Api:
          Type: Api
          Properties:
            Path: /food/planner
            Method: any
  Money/Log:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: main
      CodeUri: ./endpoints/money/logs
      Events:
        Api:
          Type: Api
          Properties:
            Path: /money/logs
            Method: any
  
