AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: The Planner API
Resources:
  Meals:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: main
      CodeUri: ./endpoints/food/meals
      Events:
        Api:
          Type: Api
          Properties:
            Path: /food/meals
            Method: any
  Ingredients:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: main
      CodeUri: ./endpoints/food/ingredients
      Events:
        Api:
          Type: Api
          Properties:
            Path: /food/ingredients
            Method: any
  MealPlanner:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: main
      CodeUri: ./endpoints/food/meal-planner
      Events:
        Api:
          Type: Api
          Properties:
            Path: /food/meal-planner
            Method: any
